### ISSUE TITLE
 Model Date Object

### ISSUE THREAD

**Issue by shaunpatterson** [infinum/datx#136]
Submitting a:

* [ ] Bug report
* [ ] Feature suggestion
* [x] Support request

I have a jsonapi service that is returning a dueDate field with `2019-08-14T00:00:00` as the value.  My model has a field "dueDate: Date".  However it is transformed into just a string.  So, model.dueDate.constructor.name prints out "String"

Is there a way to hook into model code to call "new Date()" on this field?

**Comment by DarkoKukovec** [comment]
The models are not doing any object initialization for you.
There are two ways to achieve the thing you want:

1. use the preprocess method
```typescript
public static preprocess(data) {
  return {
    ...data,
    attributes: {
      ...data.attributes,
      dueDate: new Date(data.attributes.dueDate),
    },
  };
}
```

2. Use a getter/setter
```typescript
@prop
private dueDate: Date;

@computed
public get dueDateObj(): Date {
  return new Date(this.dueDate)
}

public set dueDateObj(date: Date) {
  this.dueDate = date.toISOString();
}
```

I would recommend the second option because it will automatically work with the save method and model updates. Since the `preprocess` method is called only on model initialization it will mot be called again if you fetch the model next time. Also, if you want to save the model to the server, you would need to take care of data serialization. The getter/setter method solves those issues because the original prop is always a string and you only work with a temporary value.

**Comment by shaunpatterson** [comment]
Yep. I considered the getter/setter method but wasn't sure it was best practice.  Thanks!
