### ISSUE TITLE
need GC method

### ISSUE THREAD

**Issue by dzy321** [infinum/datx#149]
Submitting a:

* [x] Feature suggestion

--------------
 add  GC method to collection, this method will clean data which have no subscriber

**Comment by DarkoKukovec** [comment]
I agree that there should be a way to clear the store from data that is no longer used, but the question is how to determine what is used and what is not. I don't think that subscribers are the correct metric, because a model might not be shown on screen right now, but it might show up after the next click (e.g. when the `findAll` method is used)

**Comment by dzy321** [comment]
> I agree that there should be a way to clear the store from data that is no longer used, but the question is how to determine what is used and what is not. I don't think that subscribers are the correct metric, because a model might not be shown on screen right now, but it might show up after the next click (e.g. when the `findAll` method is used)

when go to another page, previous page data is no longer used. Collection can clean useless data.

**Comment by DarkoKukovec** [comment]
That is not true for all applications. In most cases we reuse the previous data and don't load it again unless it's something that could be outdated in the meantime.
Does that mean you don't need any data anymore when you change the screen. If so, you can use the `reset()` method to clear the store.
