### ISSUE TITLE
Datx jsonapi collection + router back button issues

### ISSUE THREAD

**Issue by bradherman** [infinum/datx#167]
Submitting a:

* [ ] Bug report
* [ ] Feature suggestion
* [x] Support request

--------------

If this is a bug report, please provide as many as possible of the following info:

*(delete if not a bug report)*

* datx version - 1.0.1
* datx-jsonapi version (if used), sample API response - 1.0.1
* environments (browsers?, versions) where the issue happens - brave, chromium  80.0.3987.87 (Official Build) (64-bit)
* steps to reproduce - description below
* current behavior - collection executes callbacks but does not make request
* expected behavior - collection should actually make requests

I am having a weird issue with a react app with jsonapi.  I have a collection that uses fetch to make a request to grab some data from my server in the constructor.  When I hit the page for the first time or directly, the fetch method executes and pulls the data from the server... However, if I navigate to another page in the app and then move backward/forward, the fetch function callback executes, but no server call is made and the collection remains empty.  I've thrown in debugging everywhere but can't seem to pinpoint what's happening.  Code below:

```javascript
// dataStore.js
import {Collection} from 'datx'
import { config, jsonapi } from "datx-jsonapi"
import { Cookies } from 'react-cookie'

import { observer } from 'mobx-react'

import {Charge} from './Charge.js'
import {Order} from './Order.js'

const cookies = new Cookies;

class DataStore extends jsonapi(Collection) {
  constructor(props) {
    super(props)

    let jwt = null
    jwt = window.jwt
    
    config.baseUrl = "http://localhost:3000/"
    config.defaultFetchOptions = {
      headers: {
        Authorization: `Bearer ${ jwt }`,
      }
    }
    config.encodeQueryString = true
  }
}

DataStore.types = [Charge, Order];

export default DataStore;

```
```javascript
// Charge.js
import { Model, prop } from "datx"
import uuid from "node-uuid"

class Charge extends Model {
  @prop.type
  static type = 'charge';
  @prop.identifier id: uuid
  @prop stripe_id: string
  @prop   failure_code: string
}

export { Charge };
```
```javascript
import React, {Component} from 'react';
import { NavLink } from 'react-router-dom'
import { observer } from 'mobx-react';
import { observable, action, computed } from 'mobx';
import { formatters } from '../../components/Formatters';
import _ from 'lodash'

import DataStore from '../../models/DataStore.js'
import { Charge } from '../../models/Charge.js'

import Table from '../Table';

@observer
class ChargesTable extends Component {
  @observable
  loading = true

  @observable
  dataStore = new DataStore

  constructor(props) {
    super(props)

    console.log('constructing')

    this.filter = props.filter
    this.title = `Charges (${ this.filter || 'all' })`
    this.dataUrl = props.dataUrl

    console.log('prefetch')
    console.log(this.dataStore.toJSON())

    this.dataStore.fetchAll(this.dataUrl)
      .then(res => {
        console.log('fetched!')
        console.log(res)
        console.log(this.dataStore.toJSON())
        this.loading = false
      })
  }

  @computed
  get charges(): Object {
    return this.dataStore.findAll('charge')
  }

  columns = [
    {
      dataField: 'id',
      text: 'ID',
      formatter: formatters.idFormatter,
    },
    {
      dataField: 'meta.refs.client',
      text: 'Client ID',
      sort: true,
      formatter: formatters.clientFormatter,
    },
    {
      dataField: 'meta.refs.card',
      text: 'Card ID',
      formatter: formatters.cardFormatter,
    },
    {
      dataField: 'meta.refs.order',
      text: 'Order ID',
      formatter: formatters.orderFormatter,
    },
    {
      dataField: 'amount',
      text: 'Total',
      sort: true,
      formatter: formatters.currencyFormatter,
    },
    {
      dataField: 'created_at',
      text: 'Charged At',
      formatter: formatters.fullTimeFormatter,
      sort: true,
    },
  ];

  render() {
    return (
      <Table
        loading={ this.loading }
        iconClass='cil-credit-card'
        data={ this.charges }
        columns={ this.columns }
        title={ this.title }
      />
    );
  }
}

export default ChargesTable;
```

When I hit the page that render the `ChargesTable`, both `prefetch` and `fetched` console logs happen, and the first `toJSON` on the `dataStore` shows it as empty, with the second showing the result loaded into the collection.

When I navigate away and then move back/forward onto the page, the same logs happen, but both `toJSON` on the collection show it as empty.  Also, if I look at the network tab, I see that the second time (navigating back to the page) even though the `fetched` log happens, there is no new network request.  The even weirder part though is that the `res` log shows there being results!  

What am I missing!?  Pulling my hair out over this one.

**Comment by DarkoKukovec** [comment]
Hi @bradherman,

The first issue is that you're creating the store every time your component is rendered. The stores are meant to be long-lived (app state, not component state) - create it on app start, and keep it "globally", either really globally or passed trough react context or something similar, and not recreated multiple times.

Another thing that could cause issues is marking the store as observable. There is no need to do that since DatX is doing it automatically. Doing it explicitly could cause some issues - not sure if it would, but better safe than sorry.
If you need some properties on the store, you can decorate them with an observable decorator separately.

The `@prop.type` in the model should not be used with a static property. It should be used in case you have a custom type property in your model raw data itself and want to use it as a custom model type (rarely the case, probably never with jsonapi). In this case, it can be removed. I never tried decorating the static props, so I'm not sure if this might cause any issues.

Not sure why the collection is empty after the second fetch, but it could be for any number of reasons that are caused by the three things mentioned above.

As for the mysterious response with data without the network request - this is the internal caching of the jsonapi mixin. The default behavior in the browser is cache first (no network calls if the request was already done), but you can turn this off [on the collection](https://datx.dev/docs/jsonapi/jsonapi-collection#cache) or [on the request level](https://datx.dev/docs/jsonapi/jsonapi-typescript-interfaces#irequestoptions). 
This behavior is not ideal, and it [will be changed in DatX 2](https://github.com/infinum/datx/issues/131).
