### ISSUE TITLE
Example on adding model to collection?

### ISSUE THREAD

**Issue by accoleon** [infinum/datx#55]
Would appreciate a more complete example on this common workflow:

1. Add new instance of model to collection (assuming collection is observable)
2. Save model to remote server
3. Retrieve newly-added model id.

I have tried doing this (Client extends jsonapi(Model):
```javascript
const model = new Client(newClient);
model.save().then(response => {
    console.log(response);
});
```
but the response would be a Client model object with no id, while my network log would show a 201 response with json body that contains id.

Additionally, I'm not clear on the flow of this library, do you:

```javascript
const newModel = collection.add({rawData}, myModel);
newModel.save() // how do I get the newly-saved id?
```
or
```javascript
const newModel = new myModel(rawData);
newModel.save().then(response => {
    collection.add(response); 
});
```

Either doesn't work as I expected: without an id, I can't optimistically update my ui on the browser side without fetchAll(Client), since fetch(response) without an id will effectively fetch all.

**Comment by DarkoKukovec** [comment]
Hi @accoleon 

Both of the examples will work, but I would recommend the first one as it will also work in case the model has some references.
The model id is automatically replaced with the id from response when using the save method.

How did you check the id? Since you're using the `Model` class, you should be able to do it with `model.meta.id`. Alternativelly, you can use `getModelId(model)`.

Altrough all of this functionality is covered with tests, it is possible I missed something, so if `model.meta.id` doesn't work for you please provide as much info (model class setup, model init, API response) as possible so I can try to debug the issue. Thanks

**Comment by accoleon** [comment]
I spun up another test project with typescript enabled, and:
1. Using .ts, decorators, I am able to get model.meta.id (actually model.id works too) after model.save()
2. Using javascript with decorators, I can get the id using getModelId but not model.meta.id (undefined).

In my typescript project, the documented way of defining Models works correctly (mostly), while setupModel is a little bit of a mystery (it doesn't seem to setup the models correctly).

For now, I think it's easier for me to enable typescript in my project and keep working.
