### ISSUE TITLE
Adding/saving models data in datx store (IE11)

### ISSUE THREAD

**Issue by veksi** [infinum/datx#76]
`add` functionality breaks on IE11 when trying to save models data using 2 arguments call in format:
`add(data, Model)` with errors:

> Accessing the 'arguments' property of function is not allowed in strict mode

> Accessing the 'caller' property of a function or arguments object is not allowed in strict mode

**Comment by andreicek** [comment]
Workaround is:

```javascript
const model = new Model(data); 
store.add(model)
```

**Comment by DarkoKukovec** [comment]
@veksi @andreicek I checked the issue, and it seems it's due to IE11 not supporting [Array find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility) and Create React App 1 not polyfilling it correctly.
The solution should be to explicitly to import `babel-polyfill` (version 6 if CRA 1 is used) or any other array find polyfill.

**Comment by DarkoKukovec** [comment]
Added to the Troubleshooting page. Not much more I can do... https://github.com/infinum/datx/wiki/Troubleshooting#the-library-doesnt-work-in-internet-explorer-11
